version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: monthly
    groups:
      rust-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: "/packages/openvino"
    schedule:
      interval: monthly
    groups:
      openvino-build-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: swift
    directory: "/experiments/embedding-profile/apple-coreml"
    schedule:
      interval: monthly
    groups:
      apple-coreml-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
